/**
 * CyberMem Auth Sidecar
 *
 * ForwardAuth service for Traefik that validates:
 * 1. Bearer tokens (sk-xxx) against Docker Secret file (SSoT)
 * 2. Local requests bypass (localhost, *.local domains)
 *
 * Dependencies: sqlite3 (for auto-token persistence)
 */

const http = require("http");
const crypto = require("crypto");
const path = require("path");
const fs = require("fs");
const SECRET_PATH = process.env.API_KEY_FILE || "/run/secrets/om_api_key";
const DB_PATH = process.env.OM_DB_PATH || "/data/openmemory.sqlite";
const FALLBACK_TOKEN_PATH = "/data/.cybermem_token";
let cachedToken = null;
let isAutoGenerated = false;

const PORT = process.env.PORT || 3001;

// Generate a new secure token
function generateToken() {
  return `sk-${crypto.randomBytes(16).toString("hex")}`;
}

// Hash token using PBKDF2 (same algorithm as CLI)
function hashToken(token) {
  return new Promise((resolve, reject) => {
    const salt = crypto
      .createHash("sha256")
      .update("cybermem-salt-v1")
      .digest("hex")
      .slice(0, 16);
    crypto.pbkdf2(token, salt, 100000, 64, "sha512", (err, key) => {
      if (err) reject(err);
      else resolve(key.toString("hex"));
    });
  });
}

// Store token in database
async function storeTokenInDatabase(token) {
  try {
    // Check if sqlite3 module is available
    let sqlite3;
    try {
      sqlite3 = require("sqlite3");
    } catch (e) {
      console.warn("sqlite3 module not available, skipping database storage");
      return false;
    }

    const db = new sqlite3.Database(DB_PATH);
    const tokenHash = await hashToken(token);
    const tokenId = crypto.randomBytes(8).toString("hex");

    return new Promise((resolve, reject) => {
      db.serialize(() => {
        // Create table if not exists
        db.run(
          `CREATE TABLE IF NOT EXISTS access_keys (
            id TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))),
            key_hash TEXT NOT NULL,
            name TEXT DEFAULT 'default',
            user_id TEXT DEFAULT 'default',
            created_at TEXT DEFAULT (datetime('now')),
            last_used_at TEXT,
            is_active INTEGER DEFAULT 1
          )`,
        );

        // Delete any existing auto-generated tokens
        db.run("DELETE FROM access_keys WHERE name='auto-generated'", (err) => {
          if (err) console.warn("Warning cleaning old tokens:", err.message);
        });

        // Insert new token
        db.run(
          "INSERT INTO access_keys (id, key_hash, name, user_id) VALUES (?, ?, 'auto-generated', 'admin')",
          [tokenId, tokenHash],
          (err) => {
            if (err) {
              console.error("Failed to store token in database:", err.message);
              db.close();
              reject(err);
            } else {
              console.log("✅ Auto-generated token stored in database");
              db.close();
              resolve(true);
            }
          },
        );
      });
    });
  } catch (err) {
    console.error("Database token storage error:", err.message);
    return false;
  }
}

// Load token from secret file once at startup (SSoT)
async function loadSecret() {
  try {
    // 1. Check environment variable first (Direct)
    if (process.env.OM_API_KEY) {
      cachedToken = process.env.OM_API_KEY.trim();
      console.log("SSoT Token loaded from OM_API_KEY env");
      return;
    }

    // 2. Check secret/env file (Mapped)
    if (fs.existsSync(SECRET_PATH)) {
      const content = fs.readFileSync(SECRET_PATH, "utf8").trim();

      // Check if it's a shell-formatted env file (OM_API_KEY=sk-...)
      const envMatch = content.match(/OM_API_KEY=["']?(sk-[a-zA-Z0-9]+)["']?/);
      if (envMatch) {
        cachedToken = envMatch[1];
        console.log(`SSoT Token extracted from env file: ${SECRET_PATH}`);
      } else if (content && content.startsWith("sk-")) {
        // Assume raw token file
        cachedToken = content;
        console.log(`SSoT Token loaded from raw file: ${SECRET_PATH}`);
      } else if (content) {
        console.warn(
          `SECRET WARNING: ${SECRET_PATH} exists but doesn't contain a valid token format`,
        );
      }
    }

    // 3. Check fallback token file (auto-generated location)
    if (!cachedToken && fs.existsSync(FALLBACK_TOKEN_PATH)) {
      const fallbackContent = fs
        .readFileSync(FALLBACK_TOKEN_PATH, "utf8")
        .trim();
      if (fallbackContent.startsWith("sk-")) {
        cachedToken = fallbackContent;
        console.log(`SSoT Token loaded from fallback: ${FALLBACK_TOKEN_PATH}`);
        isAutoGenerated = true;
        return;
      } else {
        console.warn(
          `SECRET WARNING: ${FALLBACK_TOKEN_PATH} exists but doesn't contain a valid token format (sk-*)`,
        );
      }
    }

    // 4. Auto-generate if no token found anywhere
    if (!cachedToken) {
      console.warn("⚠️  NO TOKEN FOUND - Auto-generating security token...");
      cachedToken = generateToken();
      isAutoGenerated = true;

      // Try to persist to fallback location
      try {
        fs.writeFileSync(FALLBACK_TOKEN_PATH, cachedToken, {
          mode: 0o600,
        });
        console.log(`✅ Auto-generated token saved to ${FALLBACK_TOKEN_PATH}`);

        // Also try to store in database
        const dbSuccess = await storeTokenInDatabase(cachedToken);
        if (!dbSuccess) {
          console.warn("⚠️  Token saved to file but database storage failed");
          console.warn(
            "    You may need to manually add the token to the database",
          );
        }
      } catch (err) {
        console.error("Failed to persist auto-generated token:", err.message);
        console.error(
          "⚠️  Token is in-memory only and will be lost on restart!",
        );
      }

      const masked =
        cachedToken.substring(0, 7) + "..." + cachedToken.slice(-4);
      console.log("\n" + "=".repeat(70));
      console.log("🔐 AUTO-GENERATED SECURITY TOKEN:");
      console.log(`   ${masked}`);
      console.log("");
      console.log("Token saved to: " + FALLBACK_TOKEN_PATH);
      console.log("Retrieve the full token from Dashboard Settings or:");
      console.log(`   cat ${FALLBACK_TOKEN_PATH}`);
      console.log("=".repeat(70) + "\n");
    }
  } catch (err) {
    console.error("SECRET LOAD ERROR:", err.message);
  }
}

loadSecret();

// Verify token against SSoT (file-based)
async function verifyToken(token) {
  if (!cachedToken) {
    // Try one more time if not loaded (e.g. race condition/debug)
    loadSecret();
  }

  if (cachedToken && token === cachedToken) {
    return { userId: "admin", name: "SSoT-Admin" };
  }

  return null;
}

// Check if request is from localhost or local network
function isLocalRequest(req) {
  const forwarded = req.headers["x-forwarded-for"];
  const realIp = req.headers["x-real-ip"];
  const host = req.headers["x-forwarded-host"] || req.headers["host"] || "";
  const ip =
    forwarded?.split(",")[0]?.trim() || realIp || req.socket.remoteAddress;

  // 1. First reject Tailscale/Remote requests (.ts.net, 100.x.x.x)
  // CRITICAL: Tailscale requests (via Funnel) must NEVER be treated as local.
  // If host contains .ts.net, it's external.
  // NOTE: Legacy CYBERMEM_TAILSCALE env-flag logic was removed on purpose.
  //       We now auto-detect Tailscale by host/IP (".ts.net" / "100.x.x.x"),
  //       so .local bypass works regardless of CYBERMEM_TAILSCALE being set.
  if (
    host.includes(".ts.net") ||
    (typeof ip === "string" && ip.startsWith("100."))
  ) {
    return false;
  }

  // 2. Allow .local (mDNS) bypass for RPi LAN access
  const hostname = host.split(":")[0];
  if (hostname.endsWith(".local")) {
    return true;
  }

  // Host-based check REMOVED for security (CVE-2026-001)
  // We only trust loopback IP if not on Tailscale.

  // Allow localhost bypass ONLY for local Dev environment (Docker Desktop)
  const isDev = process.env.CYBERMEM_INSTANCE === "local";
  if (isDev && (host.startsWith("localhost") || host.startsWith("127.0.0.1"))) {
    return true;
  }

  const isLocalIp =
    ip === "127.0.0.1" ||
    ip === "::1" ||
    ip === "::ffff:127.0.0.1" ||
    ip === "localhost";

  return isLocalIp;
}

// ForwardAuth handler
const server = http.createServer(async (req, res) => {
  // Health check
  if (req.url === "/health") {
    res.writeHead(200, { "Content-Type": "application/json" });
    res.end(
      JSON.stringify({
        status: "ok",
        mode: "token-auth",
        tokenSource: isAutoGenerated ? "auto-generated" : "configured",
      }),
    );
    return;
  }

  // Token info endpoint (metadata only — never expose raw token over HTTP)
  if (req.url === "/token-info") {
    if (!isLocalRequest(req)) {
      res.writeHead(403, { "Content-Type": "application/json" });
      res.end(JSON.stringify({ error: "Forbidden - localhost only" }));
      return;
    }

    const masked = cachedToken
      ? cachedToken.substring(0, 7) + "..." + cachedToken.slice(-4)
      : null;
    res.writeHead(200, { "Content-Type": "application/json" });
    res.end(
      JSON.stringify({
        tokenSource: isAutoGenerated ? "auto-generated" : "configured",
        tokenPrefix: masked,
        fallbackPath: FALLBACK_TOKEN_PATH,
        message: isAutoGenerated
          ? `Token was auto-generated. Read it from: cat ${FALLBACK_TOKEN_PATH}`
          : "Token is configured from deployment.",
      }),
    );
    return;
  }

  const authHeader = req.headers["authorization"];
  const apiKeyHeader = req.headers["x-api-key"];

  // 1. Resolve URI
  const requestUri = req.headers["x-forwarded-uri"] || req.url || "/";
  console.log(`[Auth-Sidecar] Processing ${req.method} ${requestUri}`);

  // 2. Public Paths Bypass
  // We allow Dashboard roots, login paths and essential assets to bypass SSoT token check
  // The Dashboard itself handles its own session auth.
  const prefixPublicPaths = [
    "/auth",
    "/api/auth",
    "/api/health",
    // "/api/metrics", // LEAK FIXED
    // "/api/stats",   // LEAK FIXED
    "/api/settings",
    "/_next",
    "/favicon",
    "/static",
    "/public",
    "/health",
    "/login",
    // "/metrics",     // LEAK FIXED
    "/clients.json",
  ];

  const exactPublicPaths = ["/"];

  const isPublic =
    exactPublicPaths.includes(requestUri) ||
    prefixPublicPaths.some((p) => requestUri.startsWith(p));

  if (isPublic) {
    console.log(`[Auth-Sidecar] ✅ Public bypass: ${requestUri}`);
    res.writeHead(200, { "X-Auth-Method": "public" });
    res.end();
    return;
  }

  // 3. Local bypass
  const isK3d = process.env.CYBERMEM_INSTANCE === "k3d";
  if (!isK3d && isLocalRequest(req)) {
    console.log(`[Auth-Sidecar] ✅ Local bypass: ${requestUri}`);
    res.writeHead(200, {
      "X-Auth-Method": "local",
      "X-User-Id": "local",
    });
    res.end();
    return;
  }

  // 4. Token Auth Verification Helper
  const verifyRequestToken = async (received) => {
    if (!received) return null;
    const result = await verifyToken(received);
    if (!result) {
      console.log(
        `[Auth-Sidecar] DEBUG Mismatch: received [${received.substring(0, 5)}...] (len:${received.length}) vs cached [${cachedToken?.substring(0, 5)}...] (len:${cachedToken?.length})`,
      );
    }
    return result;
  };

  if (authHeader?.startsWith("Bearer ")) {
    const token = authHeader.substring(7);
    const result = await verifyRequestToken(token);
    if (result) {
      console.log(
        `[Auth-Sidecar] ✅ Auth OK (Bearer): ${result.name || result.userId}`,
      );
      res.writeHead(200, {
        "X-User-Id": result.userId,
        "X-Auth-Method": "token",
        "X-Token-Name": result.name || "",
      });
      res.end();
      return;
    }
  }

  if (apiKeyHeader?.startsWith("sk-")) {
    const result = await verifyRequestToken(apiKeyHeader);
    if (result) {
      console.log(
        `[Auth-Sidecar] ✅ Auth OK (X-API-Key): ${result.name || result.userId}`,
      );
      res.writeHead(200, {
        "X-User-Id": result.userId,
        "X-Auth-Method": "api-key",
        "X-Token-Name": result.name || "",
      });
      res.end();
      return;
    }
  }

  // 5. Unauthorized
  console.log(`[Auth-Sidecar] ❌ Auth FAILED: ${requestUri}`);
  res.writeHead(401, { "Content-Type": "application/json" });
  res.end(
    JSON.stringify({
      error: "Unauthorized",
      message:
        "Valid access token required. Get your token from Dashboard Settings.",
    }),
  );
});

server.listen(PORT, () => {
  console.log(`Auth sidecar (token-auth) listening on port ${PORT}`);
});
