apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o charts/cybermem/templates/ --volumes hostPath
    kompose.version: 1.37.0 (HEAD)
    traefik.enable: "true"
    traefik.http.routers.openmemory.rule: Host(`openmemory.localhost`) || PathPrefix(`/api`)
    traefik.http.services.openmemory.loadbalancer.server.port: "8080"
  labels:
    io.kompose.service: openmemory
  name: openmemory
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: openmemory
