apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o charts/cybermem/templates/ --volumes hostPath
    kompose.version: 1.37.0 (HEAD)
  labels:
    io.kompose.service: vector
  name: vector
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: vector
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o charts/cybermem/templates/ --volumes hostPath
        kompose.version: 1.37.0 (HEAD)
      labels:
        io.kompose.service: vector
    spec:
      containers:
        - image: timberio/vector:0.34.0-alpine
          name: cybermem-vector
          ports:
            - containerPort: 9091
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/vector/vector.toml
              name: vector-hostpath0
              readOnly: true
            - mountPath: /var/log/traefik
              name: traefik-logs
              readOnly: true
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /Users/mikhailkogan/cybermem/monitoring/vector/vector.toml
          name: vector-hostpath0
        - hostPath:
            path: /Users/mikhailkogan/cybermem
          name: traefik-logs
