apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o charts/cybermem/templates/ --volumes hostPath
    kompose.version: 1.37.0 (HEAD)
  labels:
    io.kompose.service: vector
  name: vector
spec:
  ports:
    - name: "9091"
      port: 9091
      targetPort: 9091
  selector:
    io.kompose.service: vector
